site_name: Berkshire-Hataway
site_author: Grupo 5 IHC 2020.2
site_description: "Um site para citarmos as melhorias so site da empresa BerkshireHataway"
theme:
  language: pt
  palette:
    primary: blue
    accent: green
  logo: assets/favicon.png
  favicon: images/favicon.png
  name: material
nav: 
  - Home: index.md
  - Análise dos Requisitos: 
    - Guias de Estilo: Analise_de_requisitos/Guia_estilo.md
    - Metas de usabilidade: Analise_de_requisitos/Metas_usabilidade.md
    - Principios Gerais de Projeto: Analise_de_requisitos/Principios_gerais_projeto.md
    - Perfil do usuário, Personas e Análise de tarefas: Analise_de_requisitos/entrega1.md
  - Design, Avaliação e Desenvolvimento: 
    - Nivel 1: 
      - Parte 1: 
        - Storyboard: Design_avaliacao_desenvolvimento/Nivel_1/Storyboard/storyboard.md
        - Planejamento da avaliação: Design_avaliacao_desenvolvimento/Nivel_1/Storyboard/Planejamento_storyboard.md
        - Resultado da avaliação: Design_avaliacao_desenvolvimento/Nivel_1/Storyboard/Resultado_storyboard.md
      - Parte 2: 
        - Analise de tarefas: Design_avaliacao_desenvolvimento/Nivel_1/Analise_tarefas/analisedetarefas.md
        - Planejamento da avaliação: Design_avaliacao_desenvolvimento/Nivel_1/Analise_tarefas/Planejamento_analise_tarefas.md
      - Termo de consentimento: Design_avaliacao_desenvolvimento/Nivel_1/termodeconsentimento.md
    - Nivel 2: 
      - Prototipo de papel: Design_avaliacao_desenvolvimento/Nivel_2/Prototipo_papel.md
      - Planejamento da avaliação: Design_avaliacao_desenvolvimento/Nivel_2/Planejamento_prototipo_papel.md
      - Relato dos resultados: Relato_de_resultados_prototipo_de_papel.md
  - Sobre: sobre.md
  