site_name: 5inko
site_author: Grupo 5 IHC 2020.2
site_description: "Um site para citarmos as melhorias so site da empresa BerkshireHataway"

nav:
    - Home: index.md
    - Sobre: sobre.md
    - Entrega1: entrega1.md
    - Entrega2: entrega2.md