site_name: BerkshireHataway
site_author: Grupo 5 IHC 2020.2
site_description: "Um site para citarmos as melhorias so site da empresa BerkshireHataway"

nav:
    - Home: index.md
    - Sobre: sobre.md
    - Perfil do usuário, Personas e Análise de tarefas: entrega1.md
    - Princípios Gerais de Projeto, Metas de usabilidade, Guia de Estilo: entrega2.md
    - Planejamento da Avaliação e do relato dos resultados: entrega3.md
    - Story Boards: storyboards.md
    - Análise de tarefas: analisedetarefas.md
    - Termo de consentimento: termodeconsentimento.md