site_name: Berkshire-Hataway

nav: 
  - Home: index.md
  - Análise dos Requisitos: 
    - Guias de Estilo: Analise_de_requisitos/Guia_estilo.md
    - Metas de usabilidade: Analise_de_requisitos/Metas_usabilidade.md
    - Principios Gerais de Projeto: Analise_de_requisitos/Principios_gerais_projeto.md
    - Perfil do usuário, Personas e Análise de tarefas: Analise_de_requisitos/entrega1.md
  - Design, Avaliação e Desenvolvimento: 
    - Nivel 1: 
      - Parte 1: 
        - Storyboard: Design_avaliacao_desenvolvimento/Nivel_1/Storyboard/storyboard.md
        - Planejamento da avaliação: Design_avaliacao_desenvolvimento/Nivel_1/Storyboard/Planejamento_storyboard.md
        - Resultado da avaliação: Design_avaliacao_desenvolvimento/Nivel_1/Storyboard/Resultado_storyboard.md
      - Parte 2: 
        - Analise de tarefas: Design_avaliacao_desenvolvimento/Nivel_1/Analise_tarefas/analisedetarefas.md
        - Planejamento da avaliação: Design_avaliacao_desenvolvimento/Nivel_1/Analise_tarefas/Planejamento_analise_tarefas.md
      - Termo de consentimento: Design_avaliacao_desenvolvimento/Nivel_1/termodeconsentimento.md
    - Nivel 2: 
      - Prototipo de papel: Design_avaliacao_desenvolvimento/Nivel_2/Prototipo_papel.md
      - Planejamento da avaliação: Design_avaliacao_desenvolvimento/Nivel_2/Planejamento_prototipo_papel.md
      - Relato dos resultados: Design_avaliacao_desenvolvimento/Nivel_2/Relato_de_resultados_prototipo_de_papel.md
    - Nível 3:
      - Planejamento de avaliação: Design_avaliacao_desenvolvimento/Nivel_3/planejamento_avaliacao_prototiṕo_alta_fidelidade.md
      - Relato dos Resultados: Design_avaliacao_desenvolvimento/Nivel_3/resultado_prototipo_alta_fidadeidade.md
  - Sobre: sobre.md
  