site_name: Interação Humano Computador Grupo 5
ite_url: https://grupocinco.com
site_author: Grupo 5 IHC 2020.2
site_description: "Um site para citarmos as melhorias so site da empresa BerkshireHataway"
repo_url: "https://github.com/Interacao-Humano-Computador/2020.2-Grupo5"

nav:
    - Home: index.md
    - About: about.md
    - entrega1: entrega1.md
theme: lux